# Generated by Django 2.2.5 on 2019-11-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.URLField(blank=True)),
                ('picture', models.ImageField(upload_to='profile_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='first_app.User')),
            ],
        ),
    ]
